Partial rewrite to make everything easier and more readable

diff --git a/magician b/magician
--- a/magician
+++ b/magician
@@ -1,67 +1,200 @@
 #!/bin/bash
-export A="$1"
-source "./metadata.mixdata"
+#set -xv
 
-# !!!
-# DO NOT MODIFY! THIS IS A DEFAULT EXAMPLE OF MAGICIAN SCRIPT
-# !!!
+#source debug_repo
 
-get() {
-	wget -c "http://example.com/$NAME-$VERSION.tar.xz" "$NAME-$VERSION.tar.xz"
-}
+if [ -f "/etc/mixture.conf" ];then
+    source "/etc/mixture.conf"
+fi
 
-unpack() {
-	# Here we will unpack tarball with source
-	ad unpacked
-	tar -xvf ./*tar* -C unpacked
-	exit "$?"
-	echo "Contents of 'unpacked'"
-	l unpacked
-}
-conf() {
-	# This is were package source should be configured
-	cd unpacked
-	cd *
-	# ./autogen.sh
-	./configure --prefix="/usr"
-	exitcode="$?"
-	if [[ "$exitcode" != 0 ]];then exit "$exitcode";fi
-	cd ..
-	exit "$?"
-}
-comp() {
-	# This function builds a package
-	cd unpacked
-	cd *
-	make -j"$PROC"
-	exitcode="$?"
-	if [[ "$exitcode" != 0 ]];then exit "$exitcode";fi
-	cd ..
-	exit "$?"
-}
-setup() {
-	# Here we're going to install a package to local database and set up some things (if needed)
-	cd unpacked
-	cd *
-	make DESTDIR="$INSTALLTO" install
-	exitcode="$?"
-	if [[ "$exitcode" != 0 ]];then exit "$exitcode";fi
-	cd ..
-}
+if [[ "$1" != "help" && "$1" != "build" && "$1" != "package" && "$1" != "rm-build" && "$1" != "rm-download" ]];then
+	echo "Unknown operation. Type '$0 help' to get help."
+	exit 1
+fi
 
-case "$A" in
-	"get")
-		get;;
-	"unpack")
-		unpack;;
-	"conf")
-		conf;;
-	"comp")
-		comp;;
-	"setup")
-		setup;;
-	*)
-		echo "Unknown operation."
+# Define colors
+WHI="\e[1;37m"
+RED="\e[1;31m"
+GRN="\e[1;32m"
+YLW="\e[1;33m"
+BLU="\e[1;34m"
+NC="\e[0m"
+
+CHECKERR() {
+	if [[ $? != 0 ]]
+	then
+		echo -en "Failed to process a package. \nPlease, see the log file: $LOG_FILE \n"
 		exit 1
-		;;
-esac
+	fi
+}
+
+if [[ ! -e "./mixture" ]];then
+	echo "Missing mixture file! Can't continue!"
+	exit 1
+fi
+
+if [[ "$1" == "build" ]]; then
+		export PKG_NAME=`basename $PWD`
+		export PACKAGE_DIR="$PWD"
+		export LOG_DIR="$PWD/LOG"
+		export LOG_FILE="$LOG_DIR/building.mixlog"
+		export BUILD_DIR="$PWD/BUILD"
+		export OUTPUT_DIR="$PWD/OUTPUT"
+		export DOWNLOAD_DIR="$PWD/DOWNLOAD"
+
+		echo -e "${BLU}- BUILDING ${NC}"
+		echo -ne "${WHI}"
+		echo -e "Logging file:         $LOG_FILE"
+		echo -e "Build directory:      $BUILD_DIR"
+		echo -e "Download directory:   $DOWNLOAD_DIR"
+		echo -e "Output fs location:   $OUTPUT_DIR"
+		echo -ne "${NC}"
+		echo -e ""
+
+		# Recreate building log
+		if [[ -e "$LOG_FILE" || -e "$LOG_DIR" ]];then rd -r "$LOG_DIR"; fi
+		ad -p "$LOG_DIR"
+		af "$LOG_FILE"
+
+		# Create or recreate directories
+		if [[ -e "$OUTPUT_DIR" ]];then rd -r "$OUTPUT_DIR"; fi
+		ad -p "$OUTPUT_DIR"
+		if [[ -e "$DOWNLOAD_DIR/unpacked" ]];then rd -r "$DOWNLOAD_DIR/unpacked"; fi
+		ad -p "$DOWNLOAD_DIR/unpacked"
+		
+		# Remove files from previous build
+		if [[ -f "$PACKAGE_DIR/$PKG_NAME.mix" ]];then rf "$PACKAGE_DIR/$PKG_NAME.mix"; fi
+		if [[ -f "$PACKAGE_DIR/$PKG_NAME-files.mixdata" ]];then rf "$PACKAGE_DIR/$PKG_NAME-files.mixdata"; fi
+
+		# Source variables from the mixture script
+		echo -e "- Sourcing the mixture file..." | tee -a "$LOG_FILE"
+		source "$PACKAGE_DIR/mixture" "none"
+
+		# Download files listed in mixture to the DOWNLOAD directory
+		echo -e "- Downloading sources..." | tee -a "$LOG_FILE"
+		cd "$DOWNLOAD_DIR" || exit 1
+		index=1
+		for res in "${DOWNLOAD[@]}"; do
+			curl -C - "$res" -Lo "$index-$NAME-$VERSION" | tee -a "$LOG_FILE"
+			#wget -c "$res" -O "$index-$NAME-$VERSION"
+			CHECKERR $?
+			index=$((++index))
+		done
+
+		# Unpack files in DOWNLOAD/unpacked
+		echo -e "- Unpacking sources..." | tee -a "$LOG_FILE"
+		ad -p "$DOWNLOAD_DIR/unpacked" | tee -a "$LOG_FILE"
+		index=1
+		continueloop=true
+		while [[ $continueloop == true ]];do
+			if [[ -f "$index-$NAME-$VERSION" ]]; then
+				tar -xhvf "$index-$NAME-$VERSION" -C "$DOWNLOAD_DIR/unpacked" | tee -a "$LOG_FILE"
+				CHECKERR $?
+			else
+				continueloop=false
+			fi
+			index=$((++index))
+		done
+
+		# Build from source
+		cd "$DOWNLOAD_DIR/unpacked/" || exit 1
+		cd * || exit 1
+
+		echo -e "- Configuring sources..." | tee -a "$LOG_FILE"
+		bash "$PACKAGE_DIR"/mixture conf | tee -a "$LOG_FILE"
+		CHECKERR $?
+		echo -e "- Compiling sources..." | tee -a "$LOG_FILE"
+		PROC="$(nproc)" CFLAGS="$CFLAGS" CXXFLAGS="CXXFLAGS"  bash "$PACKAGE_DIR"/mixture comp | tee -a "$LOG_FILE"
+		CHECKERR $?
+		echo -e "- Installing sources into temproot..." | tee -a "$LOG_FILE"
+		INSTALLTO="$OUTPUT_DIR" bash "$PACKAGE_DIR"/mixture setup | tee -a "$LOG_FILE"
+		CHECKERR $?
+
+		echo -e "${GRN}PACKAGE BUILT SUCCESSFULLY!${NC}"
+		echo "To remove unnecessary build directory, run 'mixture rm-build'"
+		echo "To remove unnecessary download directory, run 'mixture rm-download'"
+		echo "To make a package, run 'mixture package'"
+
+elif [[ "$1" == "package" ]]; then
+		export PKG_NAME=`basename $PWD`
+		export PACKAGE_DIR="$PWD"
+		export LOG_DIR="$PWD/LOG"
+		export LOG_FILE="$LOG_DIR/packaging.mixlog"
+		export BUILD_DIR="$PWD/BUILD"
+		export OUTPUT_DIR="$PWD/OUTPUT"
+		export DOWNLOAD_DIR="$PWD/DOWNLOAD"
+
+		echo -e "${BLU}- PACKAGING ${NC}"
+		echo -ne "${WHI}"
+		echo -e "Logging file:         $LOG_FILE"
+		echo -e "Build directory:      $BUILD_DIR"
+		echo -e "Download directory:   $DOWNLOAD_DIR"
+		echo -e "Output fs location:   $OUTPUT_DIR"
+		echo -ne "${NC}"
+
+		# Source variables from mixture file
+		echo -e "- Sourcing the mixture file..." | tee -a "$LOG_FILE"
+		source "$PACKAGE_DIR/mixture" "none"
+
+		# Make a proper installation package
+		echo -e "  Making a tarball..." | tee -a "$LOG_FILE"
+		cd "$OUTPUT_DIR/" || exit 1
+		tar -cJvf "$PACKAGE_DIR/$PKG_NAME.mix" "." | tee -a "$LOG_FILE"
+		CHECKERR $?
+		filelist=$(tar -Jtf "$PACKAGE_DIR/$PKG_NAME.mix" | tail -n +2)
+		for file in $filelist ;do 
+			if [[ ! -d "$file" ]];then
+				sha512sum "$file" >> "$PACKAGE_DIR/$PKG_NAME-files.mixdata"
+			fi
+		done
+		CHECKERR $?
+
+		cd "$PACKAGE_DIR" || exit 1
+		sha512sum "$PKG_NAME.mix" > "$PKG_NAME.mix.sha512"
+		CHECKERR $?
+		echo -e "${GRN}PACKAGE CREATED SUCCESSFULLY!${NC}"
+		echo "To remove unnecessary build directory, run 'mixture rm-build'"
+		echo "To remove unnecessary download directory, run 'mixture rm-download'"
+		echo "To remove unnecessary package filesystem, run 'mixture rm-output'"
+		echo "To install it into root, use program 'mix'"
+
+elif [[ "$1" == "rm-build" ]];then
+		export PKG_NAME=`basename $PWD`
+		export PACKAGE_DIR="$PWD"
+		export LOG_DIR="$PWD/LOG"
+		export LOG_FILE="$LOG_DIR/building.mixlog"
+		export BUILD_DIR="$PWD/BUILD"
+		export OUTPUT_DIR="$PWD/OUTPUT"
+		export DOWNLOAD_DIR="$PWD/DOWNLOAD"
+
+		echo -e "${WHI}- CLEANING UP ${NC}"
+		rd -r "$BUILD_DIR"
+		rf "$LOG_FILE"
+
+elif [[ "$1" == "rm-download" ]];then
+		export PKG_NAME=`basename $PWD`
+		export PACKAGE_DIR="$PWD"
+		export LOG_DIR="$PWD/LOG"
+		export LOG_FILE="$LOG_DIR/building.mixlog"
+		export BUILD_DIR="$PWD/BUILD"
+		export OUTPUT_DIR="$PWD/OUTPUT"
+		export DOWNLOAD_DIR="$PWD/DOWNLOAD"
+
+		echo -e "${WHI}- CLEANING UP ${NC}"
+		rd -r "$DOWLOAD_DIR"
+
+elif [[ "$1" == "rm-output" ]];then
+		export PKG_NAME=`basename $PWD`
+		export PACKAGE_DIR="$PWD"
+		export LOG_DIR="$PWD/LOG"
+		export LOG_FILE="$LOG_DIR/packaging.mixlog"
+		export BUILD_DIR="$PWD/BUILD"
+		export OUTPUT_DIR="$PWD/OUTPUT"
+		export DOWNLOAD_DIR="$PWD/DOWNLOAD"
+
+		echo -e "${WHI}- CLEANING UP ${NC}"
+		rf "$LOG_FILE"
+		rd -r "$OUTPUT_DIR"
+		rf "$PACKAGE_DIR/$PKG_NAME.mix"
+		rf "$PACKAGE_DIR/$PKG_NAME-files.mixdata"
+fi
diff --git a/mix b/mix
--- a/mix
+++ b/mix
@@ -1,15 +1,13 @@
 #!/bin/bash
 #set -xv
-source default_config
+source debug_config
 source default_repo
-if [ -f "/etc/mixture.conf" ];then
-    source "/etc/mixture.conf"
+
+if [ -f "/etc/mix/mix.conf" ];then
+    source "/etc/mix/mix.conf"
 fi
-if [ -f "/etc/mix.conf" ];then
-    source "/etc/mix.conf"
-fi
-if [ -f "/etc/mix-repos.conf" ];then
-    source "/etc/mix-repos.conf"
+if [ -f "/etc/mix/repos.conf" ];then
+    source "/etc/mix/repos.conf"
 fi
 
 if [ -z "$1" ];then
@@ -22,7 +20,9 @@ if [[ -z "$2" ]];then
 		exit 1
 	fi
 fi
-# Settings from "mixture"
+
+# Settings from "mix.conf"
+# Some basic directories
 if [ -z "$ROOT" ];then
 	export ROOT="/"
 fi
@@ -32,17 +32,13 @@ fi
 if [ -z "$VAR" ];then
 	export VAR="$ROOT/var"
 fi
-if [ -z "$SRC" ];then
-	export SRC="$USR/src/mixtures"
+# This is where repositories are being saved locally
+if [ -z "$LOCAL_REPO" ];then
+	export PKG="$VAR/cache/mix/local_repo"
 fi
-if [ -z "$DATA" ];then
-	export DATA="$VAR/cache/mix/data"
-fi
-if [ -z "$PKG" ];then
-	export PKG="$VAR/cache/mix/pkgs"
-fi
-if [ -z "$LI" ];then
-	export LI="$VAR/cache/mix/localindex"
+# This is where system status is saved
+if [ -z "$STATUS" ];then
+	export DATA="$VAR/cache/mix/status"
 fi
 
 # Define colors
@@ -54,71 +50,82 @@ BLU="\e[1;34m"
 NC="\e[0m"
 
 # Create some required files for mixture if they don't exist yet
-if [[ ! -f "$LI"/installed-list ]]; then
-	ad "$LI"
+if [[ ! -f "$STATUS"/installed-list ]]; then
+	ad -i -p "$LI"
 	af "$LI/installed-list"
 fi
-if [[ "$ROOT" != /* || "$USR" != /* || "$VAR" != /* || "$SRC" != /* || "$DATA" != /* || "$PKG" != /* || "$LI" != /* ]];then
+if [[ ! -f "$STATUS"/installed-manually-list ]]; then
+	ad -i -p "$LI"
+	af "$LI/installed-manually-list"
+fi
+if [[ "$ROOT" != /* || "$USR" != /* || "$VAR" != /* || "$LOCAL_REPO" != /* || "$STATUS" != /* ]];then
 	echo "Non-absolute paths found in configuration!"
 	exit 1
 fi
 
-# Choose if you want to compile or just install stuff
-if [ -z "$PREFER_BUILD" ];then
-	export PREFER_BUILD=false
-fi
+ad -i "$ROOT" "$USR" "$VAR" "$SRC" "$LOCAL_REPO" "$STATUS"
 
-ad "$ROOT" "$USR" "$VAR" "$SRC" "$PKG" "$LI" &> /dev/null
-
-chckerr() {
-	if [[ "$?" != 0 ]]
+CHECKERR() {
+	if [[ $1 != 0 ]]
 	then
-		echo -en "Failed to build a package. \nPlease, see the log file: $MIXBLD/building.log\n"
+		echo -en "${RED}Installation unexpectedly failed!${NC}\nReport this issue to the package maintainer!\n"
 		exit 1
 	fi
 }
 
-echo -e "${GNR}>>> ${WHI}$2${NC}"
 if [[ "$1" == "install" ]]; then
-	echo -e "- PREPARING"
-    for PKG in "${@:2}"
-    do
-        echo "$PKG"
-        if [[ ! -d "$SRC/$PKG" ]];then
-			echo "Package with supplied name cannot be found!"
+	# Check existance of all packages requested by user
+	for PKG in "${@:2}"; do
+		echo "- Checking existence: $PKG"
+		if [[ ! -d "$LOCAL_REPO/$PKG" ]];then
+			echo "$PKG: Package could not be found!"
 			exit 1
-		else
-			export MIXBLD="$SRC/$PKG"
-			export MIXPKG="$PKG/$PKG.mix"
-			export MIXDATA="$DATA/$PKG/"
 		fi
-		echo -e "  Resolving dependencies for $PKG..." | tee -a "$MIXBLD/building.log"
-        source "$MIXDATA/deps.mixdata"
-        for DEPENDENCY in "${COMPILE[@]}"
-        do
-            echo "$DEPENDENCY"
-        done
-    done
-    for PKG in "${@:2}"
-    do
-        echo "$PKG"
-        if [[ ! -d "$SRC/$PKG" ]];then
-			echo "Package with supplied name cannot be found!"
-			exit 1
-		else
-			export MIXBLD="$SRC/$PKG"
-			export MIXPKG="$PKG/$PKG.mix"
-			export MIXDATA="$DATA/$PKG/"
-		fi
-		echo -e "- INSTALLING: $PKG"
-		echo -e "  Build directory:    $MIXBLD"
-		echo -e "  Ready package path: $MIXPKG"
-		echo -e "  Metadata directory: $MIXDATA"
-		echo -e ""
-		echo -e "  Checking dependency tree..." | tee -a "$MIXBLD/building.log"
-        source "$MIXDATA/deps.mixdata"
+	done
+	# Check dependencies
+	for PKG in "${@:2}"; do
+		echo "- Checking dependencies: $PKG"
+		source "$LOCAL_REPO/$PKG/mixture"
+		for DEP in ${RUNTIME_DEPS} ; do
+			echo "NOTICE: Package $PKG depends on $DEP"
+		done
+	done
+	echo "Abort!"			
+	exit 0
 
-    done
+	echo "- Cheking intergrity..."
+	cd "$PKG" || exit 1
+	sha512sum -c "$2".mix.sha512 --status
+	CHECKERR $?
+	echo "- Unpacking .mix package..."
+	ad -p "$MIXPKG"
+	tar -xhf "$PKG/$2.mix" -C "$MIXPKG"
+	chckerr
+	cd "$MIXPKG" || exit 1
+	echo "- Checking file collisions..."
+	# Check if package already exists
+	source "./metadata.mixdata"
+	if grep "$2:$VERSION" "$LI/installed-list" -xq; then
+		echo "This package is already installed!"
+		exit 1
+	fi
+	# Check if file collides with another file from another package
+	while read -r f; do
+		e=0
+		if [ -f "$ROOT/$f" ];then
+			while read -r p;do
+				pkg="$(echo "$p" | awk -F':' '{ print $1 }')"
+				if [[ "$pkg" != "$2" ]]; then
+					while read -r f;do
+						filename="$(echo "$f" | awk -F'  ' '{ print $2 }')"
+						echo "File $ROOT/$filename is already reserved by a package \"$pkg\""
+						e=1
+					done < "$DATA"/"$2"/filelist.mixdata
+				fi
+			done < "$LI"/installed-list
+		fi
+		if [[ "$e" != 0 ]];then
+			exit 1
 elif [[ "$1" == "remove" ]]; then
 	echo -e ">> TODO!"
 elif [[ "$1" == "update" ]]; then
